databases:
  - name: newsapp
    databaseName: newsapp
    user: newsapp

services:
  - type: web
    name: newsapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn newsapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newsapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
